{
 "title": "Habbit Tracker",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Apartment Activity",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT t1.locName, SUM(t2.duration) FROM sensors t1, events t2 WHERE t1.sensorId = t2.sensorId AND $__timeFilter(triggerStart, triggerEnd) GROUP BY locName ORDER BY sum(t2.duration) DESC;\n"
    }
   ]
  },
  {
   "title": "Recent Activity",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT t2.idx, t1.locName, t2.triggerStart, t2.triggerEnd, t2.duration \nFROM sensors t1, events t2 \nWHERE t1.sensorId = t2.sensorId AND \n      $__timeFrom() < triggerStart\nORDER BY idx DESC;"
    }
   ]
  },
  {
   "title": "Activity variation (Time)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT t1.locName, t2.difference FROM sensors t1, differences t2 WHERE t1.sensorId = t2.sensorId AND $__timeFilter(from_date, to_date) ORDER BY t2.difference DESC;"
    }
   ]
  },
  {
   "title": "Sensors Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT locName as \"Location\", Status as \"Status\", ipAddress as \"IP Address\" FROM sensors ORDER BY sensorId ASC;"
    }
   ]
  },
  {
   "title": "Activity variation (Percentage)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT t1.locName, t2.percentage FROM sensors t1, differences t2 WHERE t1.sensorId = t2.sensorId AND $__timeFilter(from_date, to_date) ORDER BY t2.percentage DESC;"
    }
   ]
  },
  {
   "title": "Activity variation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  triggerStart AS \"time\",\n  activity AS metric,\n  duration\nFROM activities\nWHERE\n  $__timeFilter(triggerStart)\nORDER BY triggerStart"
    }
   ]
  }
 ]
}